### ISSUE TITLE
Goreplace sometimes dies with a traceback

### ISSUE THREAD

**Issue by vsolovyov** [piranha/goreplace#37]
Apparently it started after upgrading to macOS 10.12:

```
andrey@andreymac ~/work/prophy/prophy> gr 'get_article2tfidf_vector'
Skipping datalib/tests/testdata/sw_ontology.json, too big: 13859118

src/prophy/clusters/article_metrics.py
 79:def get_article2tfidf_vector(article2property: TArticle2Property,
116:        return get_article2tfidf_vector(article2property=article2property,
Skipping src/tests/latex_archives/with_text_and_refs/1203.3562v1, too big: 11284480

failed MSpanList_Insert 0x279c00 0x947226add66d 0x0
fatal error: MSpanList_Insert

goroutine 16 [running]:
runtime.throw(0x22ca1b)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/panic.c:520 +0x69 fp=0xc20807f060 sp=0xc20807f048
runtime.MSpanList_Insert(0x242c28, 0x279c00)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/mheap.c:618 +0x8a fp=0xc20807f088 sp=0xc20807f060
MHeap_FreeLocked(0x23ec20, 0x279c00)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/mheap.c:447 +0x1a6 fp=0xc20807f0c8 sp=0xc20807f088
MHeap_AllocLocked(0x23ec20, 0x156, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/mheap.c:257 +0x288 fp=0xc20807f108 sp=0xc20807f0c8
runtime.MHeap_Alloc(0x23ec20, 0x156, 0x10100000000)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/mheap.c:178 +0x7b fp=0xc20807f130 sp=0xc20807f108
largealloc(0xc200000001, 0xc20807f1e0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/malloc.goc:224 +0xa2 fp=0xc20807f178 sp=0xc20807f130
runtime.mallocgc(0x2aa800, 0x107141, 0x1)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/malloc.goc:169 +0xb6 fp=0xc20807f1e0 sp=0xc20807f178
cnew(0x107140, 0x2aa800, 0x1)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/malloc.goc:836 +0xc1 fp=0xc20807f200 sp=0xc20807f1e0
runtime.cnewarray(0x107140, 0x2aa800)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/malloc.goc:849 +0x3a fp=0xc20807f220 sp=0xc20807f200
makeslice1(0x1000e0, 0x2aa800, 0x2aa800, 0xc20807f280)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/slice.goc:55 +0x4d fp=0xc20807f238 sp=0xc20807f220
runtime.makeslice(0x1000e0, 0x2aa800, 0x2aa800, 0x0, 0x2aa800, 0x2aa800)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/slice.goc:36 +0xb3 fp=0xc20807f268 sp=0xc20807f238
main.(*GRVisitor).GetFileAndContent(0xc208025320, 0xc208036f40, 0x38, 0x283488, 0xc208168230, 0xc208038050, 0x0, 0x0, 0x0)
	/Users/piranha/dev/go/src/goreplace/goreplace.go:235 +0x125 fp=0xc20807f360 sp=0xc20807f268
main.(*GRVisitor).VisitFile(0xc208025320, 0xc208036f40, 0x38, 0x283488, 0xc208168230)
	/Users/piranha/dev/go/src/goreplace/goreplace.go:190 +0x3d9 fp=0xc20807f4b8 sp=0xc20807f360
main.(*GRVisitor).Walk(0xc208025320, 0xc208036f40, 0x38, 0x283488, 0xc208168230, 0x0, 0x0, 0x0, 0x0)
	/Users/piranha/dev/go/src/goreplace/goreplace.go:148 +0x137 fp=0xc20807f4f8 sp=0xc20807f4b8
main.*GRVisitor.Walk·fm(0xc208036f40, 0x38, 0x283488, 0xc208168230, 0x0, 0x0, 0x0, 0x0)
	/Users/piranha/dev/go/src/goreplace/goreplace.go:121 +0x7f fp=0xc20807f548 sp=0xc20807f4f8
path/filepath.walk(0xc208036f40, 0x38, 0x283488, 0xc208168230, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:343 +0x8c fp=0xc20807f690 sp=0xc20807f548
path/filepath.walk(0xc208174ae0, 0x2b, 0x283488, 0xc208168410, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:368 +0x4f5 fp=0xc20807f7d8 sp=0xc20807f690
path/filepath.walk(0xc2081ba1c0, 0x18, 0x283488, 0xc208168140, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:368 +0x4f5 fp=0xc20807f920 sp=0xc20807f7d8
path/filepath.walk(0xc208000d10, 0x9, 0x283488, 0xc208168eb0, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:368 +0x4f5 fp=0xc20807fa68 sp=0xc20807f920
path/filepath.walk(0xc2080815d5, 0x3, 0x283488, 0xc20841bcc0, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:368 +0x4f5 fp=0xc20807fbb0 sp=0xc20807fa68
path/filepath.walk(0x15bdd0, 0x1, 0x283488, 0xc20801ae60, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:368 +0x4f5 fp=0xc20807fcf8 sp=0xc20807fbb0
path/filepath.Walk(0x15bdd0, 0x1, 0xc20807fda8, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/path/filepath/path.go:390 +0xe5 fp=0xc20807fd60 sp=0xc20807fcf8
main.searchFiles(0xc2080840a0, 0x283538, 0xc208054680, 0x283628, 0xc20801ac30)
	/Users/piranha/dev/go/src/goreplace/goreplace.go:121 +0xda fp=0xc20807fdc0 sp=0xc20807fd60
main.main()
	/Users/piranha/dev/go/src/goreplace/goreplace.go:101 +0x69a fp=0xc20807ff50 sp=0xc20807fdc0
runtime.main()
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/proc.c:247 +0x11a fp=0xc20807ffa8 sp=0xc20807ff50
runtime.goexit()
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/proc.c:1445 fp=0xc20807ffb0 sp=0xc20807ffa8
created by _rt0_go
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 19 [finalizer wait]:
runtime.park(0x1ce00, 0x22f230, 0x22e5e9)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x22f230, 0x22e5e9)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/proc.c:1445
zsh: exit 2     gr 'get_article2tfidf_vector'
```

Looks like both goreplace 2.3 and 2.4 are affected (haven't tried other versions).

**Comment by Valve** [comment]
I should say it's not "sometimes" it dies for me every other run, making the app unusable. Please have a look into this issue, if possible, I would very much appreciate this. I'm on Sierra 10.12.2

**Comment by piranha** [comment]
Damn, I still have not update to 10.12, and I literally have no idea what's going on here - it's something inside of Go's libraries... I wonder if updating Go will help. I've [released](https://github.com/piranha/goreplace/releases/tag/2.5) a new version, compiled by Go 1.7.4, maybe it will help.

**Comment by Valve** [comment]
Thanks!

I will test it later this week and let you know

**Comment by Valve** [comment]
Looks fine for me, @vsolovyov is it working for you?

**Comment by vsolovyov** [comment]
@Valve it does work for me (my colleague, actually, I haven't updated to 10.12 myself). I think this issue can be closed
